logging:
  level:
    root: INFO
spring:
  profiles:
    active: local
  mvc:
    format:
      date: yyyy-MM-dd
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
